### PR TITLE
Aozdemir seamless 908 folder view

### PR DESCRIPTION
**Pull request by abdullahozdemir**

### CODE REVIEW

**Review by orhanharman — CHANGES_REQUESTED** [review]
I think we should not change the username and password, everyone is gonna use the same username and password..

**Review by ismailsavcan — CHANGES_REQUESTED** [review]
Do not change username. It should be Employee61. Update it as Employee61 the make another request

**Review by ismailsavcan — APPROVED** [review]
ok, I reviewed

**Comment by orhanharman** [comment]
Dear İsmail abi, you have approved the pull request but the username is still 'Employee11' on this request, if we merge it to master, everyone is gonna get the changes to themselves as 'Employee11', I think we should not merge this request untill it the username changes to 'Employee61'

**Pull request merged**
