### PR TITLE
İsmet seamless 916 tasks

### PR DESCRIPTION
**Pull request by ismailsavcan**

### CODE REVIEW

**Comment by ismetgunes** [comment]
As far as I know, my deck module functionalty finished

**Review by HilmiUnn — COMMENTED** [review]
That's great as always

**Review by HilmiUnn — APPROVED** [review]
No issue, great

**Review by ismailsavcan — COMMENTED** [review]
Good Job Ismet Hocam

**Review by ismailsavcan — COMMENTED** [review]
Ok

**Review by ismailsavcan — COMMENTED** [review]
Ok

**Review by ismailsavcan — COMMENTED** [review]
Ok

**Review by ismailsavcan — COMMENTED** [review]
I reviewed

**Comment by ismetgunes** [comment]
> Good Job Ismet Hocam

Thaks abi, I'm so sorry, I'm late to reply.  I wish you good work

**Pull request closed without merging**
